### PR TITLE
SyncClientX

### PR DESCRIPTION
**Pull request by ramtinak**
Add realtime support for DM via mqtt [dropping support for realtime WebSocket]
Also you can send message to DM as well.
This is my final code, you have to update it with your code.
This code was ported from>
https://github.com/Nerixyz/instagram_mqtt

Good luck.
Have a good day.

### CODE REVIEW

**Comment by ramtinak** [comment]
I forgot something, note that some of information changed because I;ve created cert file in my PC. so remove them

**Comment by huynhsontung** [comment]
This looks awesome! But I do have a couple of questions.

- Is Instagram retiring WebSocket realtime endpoint? This is the method Instagram uses for their web client. WebSocket has some sweet support in UWP that adds extra safety and reliability. I prefer working with WebSocket to barebone `StreamSocket` when possible.
- Adding onto the first point, what is the benefits of this transition exactly? The current sync client is doing its job, which is to be a realtime event source for realtime changes (like incoming messages and user presence), perfectly. I can see it's possible to send text over a `PUBLISH` message but what's wrong with just making a request to `/direct_v2/threads/broadcast/text/`?

**Comment by ramtinak** [comment]
- Nope, Instagram doesn't want to retire their WebSocket endpoint [at least as I know~]
But as I saw in Instagram API in the past few years, you may get blocked so that's why I've integrate it with actual mqtt realtime for android.
The point is that we are using Android API so it's better to keeps things clean and use their work in our projects to prevent blocking part or any other issues.

- The SendDirectTextAsync in the messaging processor, is quite restricted [ my customers keeps telling me this ], and sometimes you may get feedback required.


Last word: I just sent this, because I just wanted to thank you for your work. Because I'm using push notifications code in my app.

Feel free to close/ leave this open for someone who is looking for this.

Best regards.

**Comment by huynhsontung** [comment]
Glad to hear that my code is helping someone. Push client is still very finicky and from my analytics, it often just gives out and stops working even with all my error handling and self-recovery implemented, at least until user restarts their machine or opens the app. Concurrency is also a big problem, Windows' background task trigger will sometimes invoke twice at the same time which ruins the running flow. I am constantly looking for ways to improve push client reliability. Please let me know if you find anything interesting regarding this aspect.

**Comment by huynhsontung** [comment]
Instagram has stopped using cookies in their app recently, which makes using websocket version of SyncClient no longer possible. Changes in this PR have been incorporated in d5d387fcd7e878eb1800ea309e1a760944f3d83f.

Closing this PR now.

**Pull request closed without merging**
